name: Firebase Functions Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install Dependencies (Root)
        run: |
          npm install -g firebase-tools
          npm ci  # Ensures clean and reproducible dependency installation at the root level

      - name: Copy src Folder to Functions
        run: |
          cp -r ./src ./functions/  # Copies the src folder and its contents to the functions folder

      - name: Inject Mongo URIs into serverDbUtils.js
        run: |
          echo "const MONGO_URI_ASIA_EAST1_TAIWAN = '${{ secrets.MONGO_URI_ASIA_EAST1_TAIWAN }}';" > ./functions/src/config/serverDbUtils.js.tmp
          echo "const MONGO_URI_EUROPE_WEST1_BELGIUM = '${{ secrets.MONGO_URI_EUROPE_WEST1_BELGIUM }}';" >> ./functions/src/config/serverDbUtils.js.tmp
          echo "const MONGO_URI_US_CENTRAL1_LOWA = '${{ secrets.MONGO_URI_US_CENTRAL1_LOWA }}';" >> ./functions/src/config/serverDbUtils.js.tmp
          cat ./functions/src/config/serverDbUtils.js >> ./functions/src/config/serverDbUtils.js.tmp  # Append the original content
          mv ./functions/src/config/serverDbUtils.js.tmp ./functions/src/config/serverDbUtils.js  # Replace original file with updated version

     

      - name: Install Dependencies (Functions)
        run: |
          cd functions  # Navigate to the functions folder
          npm ci  # Install dependencies inside the functions folder
          cd ..

      - name: Deploy to Firebase Functions
        run: |
          firebase deploy --only functions
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

      - name: Notify Deployment Success
        run: echo "Deployment to Firebase Functions completed successfully!"
